### ISSUE TITLE
Album cover shows too small

### ISSUE THREAD

**Issue by Suzamax** [hrdwrrsk/tetra-gtk-theme#26]
Tetra Gnome Shell theme shows it this way:

![Captura de pantalla de 2019-03-09 20-55-21](https://user-images.githubusercontent.com/10341605/54076650-36a47100-42ae-11e9-8cdd-7c5b74bb32bf.png)

I made a little tweak for showing it way better:
![Captura de pantalla de 2019-03-09 20-52-14](https://user-images.githubusercontent.com/10341605/54076657-5d62a780-42ae-11e9-98c5-090268ca7395.png)

Here's the CSS involved:
```scss
.media-message-cover-icon {
            icon-size: 40px !important;
	    border-radius: 2px;
	    border: 1px solid #555;
	    box-shadow: 0 0 1px #aaa;
            &.fallback {
              color: lighten($fg_color,10%);
              background-color: transparent;
              border: 0;
              border-radius: 2px;
              icon-size: 32px;
              padding: 8px; }
          }
```
